version: '3.0'

services:
  db:
    container_name: db
    image: postgres:alpine
    networks:
      - postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=web'
      - 'POSTGRES_PASSWORD=postgres'

  backend:
    networks:
      - postgres
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
networks:
  postgres:
    driver: bridge